site_name: Harshad Ghodke — Portfolio
site_url: https://hghodkephd.github.io/hg-portfolio/
theme:
  name: material
nav:
  - Home: index.md
  - Résumé: resume.md
  - Projects: projects.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
